FROM python:3

COPY requirements.txt ./
COPY pytest.ini ./
RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /test/

CMD ["/bin/bash", "-c", "coverage run --source=/app/ -m pytest -v && coverage report --show-missing"]
