FROM python:3

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY github_token /

CMD ["/bin/bash", "-c", "coverage run --source=/app/ -m pytest -v /test/ && coverage report --show-missing"]
